language: node_js
dist: trusty
node_js:
- '11.6'
before_install:
- openssl aes-256-cbc -K $encrypted_f39920166870_key -iv $encrypted_f39920166870_iv -in key.json.enc -out ./config/.firebase-key/key.json -d
