language: node_js
dist: trusty
node_js:
- '11.6'
before_install:
- openssl aes-256-cbc -K $encrypted_f39920166870_key -iv $encrypted_f39920166870_iv
  -in chat-v2-dev-firebase-adminsdk-z2x9h-37eb9c38c5.json.enc -out config/.firebase-key/chat-v2-dev-firebase-adminsdk-z2x9h-37eb9c38c5.json
  -d
