language: node_js
dist: trusty
node_js:
- '11.6'
services: mongodb
sudo: required
cache:
  directories:
  - node_modules
env:
- MONGODB_VERSION=4.0.x MONGODB_TOPOLOGY=standalone
before_install:
- openssl aes-256-cbc -K $encrypted_f39920166870_key -iv $encrypted_f39920166870_iv
  -in .firebasekey.json.enc -out .firebasekey.json -d
