version: "3.7"
### Creates a named network with the default bridge driver
# The network is shared between restheart and mongodb only
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
networks:
   backend:
   frontend:

### Create a permanent, named data volume
# This makes much easier to identify where the mongodb data is stored on host
# See: https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
volumes:
   tiledesk-datadb:
   chat21-cf:
   tiledesk-server-config2:


services:
  dashboard:
   image: tiledesk/tiledesk-dashboard
   container_name: tiledesk-dashboard
   ports:
      - "4500:80" # specify port forewarding
   networks:
         - frontend
  web-widget:
   image: chat21/chat21-web-widget:latest-remoteconfig
   container_name: chat21-web-widget
   ports:
      - "4200:80" # specify port forewarding
   networks:
      - frontend
   depends_on:
      - proxy
  ionic:
   image: chat21/chat21-ionic
   container_name: chat21-ionic
   ports:
      - "8080:80" # specify port forewarding
   networks:
      - frontend
  proxy:
    #image: nginx
    #container_name: proxy
    image: tiledesk/tiledesk-docker-proxy
    container_name: tiledesk-docker-proxy
    #volumes:
     # - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # specify port forewarding
    networks:
      - frontend
      - backend
    links:
      - ionic
      - dashboard
      - server
    command: [nginx-debug, '-g', 'daemon off;']
  cloud-functions:
   image: chat21/chat21-cloud-functions
   container_name: chat21-cloud-functions
   volumes:
     - chat21-cf:/home #persist firebase login
   ports:
     - "9005:9005" # specify port forewarding
     - "5000:5000"
  server:
    image: tiledesk/tiledesk-server:beta
    container_name: tiledesk-server
    restart: always
    networks:
         - backend
    volumes:    
        #  - type: bind
        #    source: ./
        #    target: /usr/src/app/
        - tiledesk-server-config2:/usr/src/app/confenv
      # - ./:/usr/src/app/

    #env_file:
    #     - .env
    environment: 
      - FIREBASE_PRIVATE_KEY
      - FIREBASE_CONFIG_FILE
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PROJECT_ID
      - CHAT21_ENABLED
      - CHAT21_URL
      - CHAT21_APPID
      - CHAT21_ADMIN_TOKEN
   #   - DATABASE_URI
      - MONGODB_URI=mongo
      - LOAD_DOTENV_SUBFOLDER=true
#    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: --bind_ip_all
    volumes:
      - tiledesk-datadb:/data/db
    networks:
         - backend
      ### Uncoment below if you want to map mongodb port
      #ports:
      #   - "27017:27017"
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    command: ngrok http server:3000
    networks:
     - backend
    ports:
     -  '4040:4040'
    links:
      - "server"
    #command: ngrok http server:3000
