version: "2"
services:
  app:
    container_name: tiledesk-api
    restart: always
    environment: 
      - FIREBASE_PRIVATE_KEY
      - MONGODB_URI=mongo
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
