version: "2"
### Creates a named network with the default bridge driver
# The network is shared between restheart and mongodb only
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
networks:
   backend:
   frontend:

### Create a permanent, named data volume
# This makes much easier to identify where the mongodb data is stored on host
# See: https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
volumes:
   tiledesk-datadb:


services:
  dashboard:
   image: tiledesk/tiledesk-dashboard
   container_name: tiledesk-dashboard
   ports:
      - "4500:80" # specify port forewarding
   networks:
         - frontend
  web-widget:
   image: chat21/chat21-web-widget
   container_name: chat21-web-widget
   ports:
      - "4200:80" # specify port forewarding
   networks:
      - frontend
  ionic:
   image: chat21/chat21-ionic
   container_name: chat21-ionic
   ports:
      - "8080:80" # specify port forewarding
   networks:
      - frontend
  web:
    image: nginx
    container_name: proxy
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80" # specify port forewarding
    networks:
      - frontend
    links:
      - ionic
      - dashboard
    command: [nginx-debug, '-g', 'daemon off;']
  cloud-functions:
   image: chat21/chat21-cloud-functions
   container_name: chat21-cloud-functions
  server:
    image: tiledesk/tiledesk-server:beta
    container_name: tiledesk-server
    restart: always
    networks:
         - backend
    env_file:
         - .env
    environment: 
      - FIREBASE_PRIVATE_KEY
      - FIREBASE_CONFIG_FILE
      - FIREBASE_CLIENT_EMAIL
      - FIREBASE_PROJECT_ID
      - CHAT21_ENABLED
      - CHAT21_URL
      - CHAT21_APPID
      - CHAT21_ADMIN_TOKEN
   #   - DATABASE_URI
      - MONGODB_URI=mongo
#    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: --bind_ip_all
    volumes:
      - tiledesk-datadb:/data/db
    networks:
         - backend
      ### Uncoment below if you want to map mongodb port
      #ports:
      #   - "27017:27017"
  ngrok:
    container_name: ngrok
    image: wernight/ngrok
    command: ngrok http backend:3000
    networks:
     - backend
    ports:
     -  '4040:4040'
    #links:
    #  - "server"
    #command: ngrok http server:3000
